# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: oslcapi
    build: .
    command: flask run -h 0.0.0.0
    env_file:
      - ./.flaskenv
      - ./.env
    environment:
      - DATABASE_URI=sqlite:////db/oslcapi.db
    volumes:
      - ./oslcapi:/code/oslcapi
      - ./db/:/db/
    ports:
      - "5001:5000"